/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.AirQualityLayer;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AirQualityLayerRecord extends UpdatableRecordImpl<AirQualityLayerRecord> implements Record13<Integer, String, Integer, Integer, String, Short, String, String, String, String, String, LocalDateTime, JSON> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.air_quality_layer.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.air_quality_layer.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>data.air_quality_layer.pollutant_id</code>.
     */
    public void setPollutantId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.pollutant_id</code>.
     */
    public Integer getPollutantId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>data.air_quality_layer.grid_definition_id</code>.
     */
    public void setGridDefinitionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.grid_definition_id</code>.
     */
    public Integer getGridDefinitionId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.air_quality_layer.user_id</code>.
     */
    public void setUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.user_id</code>.
     */
    public String getUserId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>data.air_quality_layer.share_scope</code>.
     */
    public void setShareScope(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.share_scope</code>.
     */
    public Short getShareScope() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>data.air_quality_layer.aq_year</code>.
     */
    public void setAqYear(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.aq_year</code>.
     */
    public String getAqYear() {
        return (String) get(6);
    }

    /**
     * Setter for <code>data.air_quality_layer.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>data.air_quality_layer.source</code>.
     */
    public void setSource(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.source</code>.
     */
    public String getSource() {
        return (String) get(8);
    }

    /**
     * Setter for <code>data.air_quality_layer.data_type</code>.
     */
    public void setDataType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.data_type</code>.
     */
    public String getDataType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>data.air_quality_layer.filename</code>.
     */
    public void setFilename(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.filename</code>.
     */
    public String getFilename() {
        return (String) get(10);
    }

    /**
     * Setter for <code>data.air_quality_layer.upload_date</code>.
     */
    public void setUploadDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.upload_date</code>.
     */
    public LocalDateTime getUploadDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>data.air_quality_layer.task_log</code>.
     */
    public void setTaskLog(JSON value) {
        set(12, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.task_log</code>.
     */
    public JSON getTaskLog() {
        return (JSON) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, Integer, Integer, String, Short, String, String, String, String, String, LocalDateTime, JSON> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, Integer, Integer, String, Short, String, String, String, String, String, LocalDateTime, JSON> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AirQualityLayer.AIR_QUALITY_LAYER.ID;
    }

    @Override
    public Field<String> field2() {
        return AirQualityLayer.AIR_QUALITY_LAYER.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return AirQualityLayer.AIR_QUALITY_LAYER.POLLUTANT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return AirQualityLayer.AIR_QUALITY_LAYER.GRID_DEFINITION_ID;
    }

    @Override
    public Field<String> field5() {
        return AirQualityLayer.AIR_QUALITY_LAYER.USER_ID;
    }

    @Override
    public Field<Short> field6() {
        return AirQualityLayer.AIR_QUALITY_LAYER.SHARE_SCOPE;
    }

    @Override
    public Field<String> field7() {
        return AirQualityLayer.AIR_QUALITY_LAYER.AQ_YEAR;
    }

    @Override
    public Field<String> field8() {
        return AirQualityLayer.AIR_QUALITY_LAYER.DESCRIPTION;
    }

    @Override
    public Field<String> field9() {
        return AirQualityLayer.AIR_QUALITY_LAYER.SOURCE;
    }

    @Override
    public Field<String> field10() {
        return AirQualityLayer.AIR_QUALITY_LAYER.DATA_TYPE;
    }

    @Override
    public Field<String> field11() {
        return AirQualityLayer.AIR_QUALITY_LAYER.FILENAME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return AirQualityLayer.AIR_QUALITY_LAYER.UPLOAD_DATE;
    }

    @Override
    public Field<JSON> field13() {
        return AirQualityLayer.AIR_QUALITY_LAYER.TASK_LOG;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getPollutantId();
    }

    @Override
    public Integer component4() {
        return getGridDefinitionId();
    }

    @Override
    public String component5() {
        return getUserId();
    }

    @Override
    public Short component6() {
        return getShareScope();
    }

    @Override
    public String component7() {
        return getAqYear();
    }

    @Override
    public String component8() {
        return getDescription();
    }

    @Override
    public String component9() {
        return getSource();
    }

    @Override
    public String component10() {
        return getDataType();
    }

    @Override
    public String component11() {
        return getFilename();
    }

    @Override
    public LocalDateTime component12() {
        return getUploadDate();
    }

    @Override
    public JSON component13() {
        return getTaskLog();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getPollutantId();
    }

    @Override
    public Integer value4() {
        return getGridDefinitionId();
    }

    @Override
    public String value5() {
        return getUserId();
    }

    @Override
    public Short value6() {
        return getShareScope();
    }

    @Override
    public String value7() {
        return getAqYear();
    }

    @Override
    public String value8() {
        return getDescription();
    }

    @Override
    public String value9() {
        return getSource();
    }

    @Override
    public String value10() {
        return getDataType();
    }

    @Override
    public String value11() {
        return getFilename();
    }

    @Override
    public LocalDateTime value12() {
        return getUploadDate();
    }

    @Override
    public JSON value13() {
        return getTaskLog();
    }

    @Override
    public AirQualityLayerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value3(Integer value) {
        setPollutantId(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value4(Integer value) {
        setGridDefinitionId(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value5(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value6(Short value) {
        setShareScope(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value7(String value) {
        setAqYear(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value8(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value9(String value) {
        setSource(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value10(String value) {
        setDataType(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value11(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value12(LocalDateTime value) {
        setUploadDate(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value13(JSON value) {
        setTaskLog(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5, Short value6, String value7, String value8, String value9, String value10, String value11, LocalDateTime value12, JSON value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AirQualityLayerRecord
     */
    public AirQualityLayerRecord() {
        super(AirQualityLayer.AIR_QUALITY_LAYER);
    }

    /**
     * Create a detached, initialised AirQualityLayerRecord
     */
    public AirQualityLayerRecord(Integer id, String name, Integer pollutantId, Integer gridDefinitionId, String userId, Short shareScope, String aqYear, String description, String source, String dataType, String filename, LocalDateTime uploadDate, JSON taskLog) {
        super(AirQualityLayer.AIR_QUALITY_LAYER);

        setId(id);
        setName(name);
        setPollutantId(pollutantId);
        setGridDefinitionId(gridDefinitionId);
        setUserId(userId);
        setShareScope(shareScope);
        setAqYear(aqYear);
        setDescription(description);
        setSource(source);
        setDataType(dataType);
        setFilename(filename);
        setUploadDate(uploadDate);
        setTaskLog(taskLog);
    }
}
