/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.ExposureFunction;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExposureFunctionRecord extends UpdatableRecordImpl<ExposureFunctionRecord> implements Record10<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.exposure_function.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.exposure_function.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.exposure_function.exposure_dataset_id</code>.
     */
    public void setExposureDatasetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.exposure_function.exposure_dataset_id</code>.
     */
    public Integer getExposureDatasetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.exposure_function.population_group</code>.
     */
    public void setPopulationGroup(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.exposure_function.population_group</code>.
     */
    public String getPopulationGroup() {
        return (String) get(2);
    }

    /**
     * Setter for <code>data.exposure_function.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.exposure_function.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.exposure_function.ethnicity_id</code>.
     */
    public void setEthnicityId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.exposure_function.ethnicity_id</code>.
     */
    public Integer getEthnicityId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>data.exposure_function.gender_id</code>.
     */
    public void setGenderId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.exposure_function.gender_id</code>.
     */
    public Integer getGenderId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>data.exposure_function.start_age</code>.
     */
    public void setStartAge(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.exposure_function.start_age</code>.
     */
    public Integer getStartAge() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>data.exposure_function.end_age</code>.
     */
    public void setEndAge(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.exposure_function.end_age</code>.
     */
    public Integer getEndAge() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>data.exposure_function.variable_id</code>.
     */
    public void setVariableId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>data.exposure_function.variable_id</code>.
     */
    public Integer getVariableId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>data.exposure_function.function_text</code>.
     */
    public void setFunctionText(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>data.exposure_function.function_text</code>.
     */
    public String getFunctionText() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ExposureFunction.EXPOSURE_FUNCTION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ExposureFunction.EXPOSURE_FUNCTION.EXPOSURE_DATASET_ID;
    }

    @Override
    public Field<String> field3() {
        return ExposureFunction.EXPOSURE_FUNCTION.POPULATION_GROUP;
    }

    @Override
    public Field<Integer> field4() {
        return ExposureFunction.EXPOSURE_FUNCTION.RACE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return ExposureFunction.EXPOSURE_FUNCTION.ETHNICITY_ID;
    }

    @Override
    public Field<Integer> field6() {
        return ExposureFunction.EXPOSURE_FUNCTION.GENDER_ID;
    }

    @Override
    public Field<Integer> field7() {
        return ExposureFunction.EXPOSURE_FUNCTION.START_AGE;
    }

    @Override
    public Field<Integer> field8() {
        return ExposureFunction.EXPOSURE_FUNCTION.END_AGE;
    }

    @Override
    public Field<Integer> field9() {
        return ExposureFunction.EXPOSURE_FUNCTION.VARIABLE_ID;
    }

    @Override
    public Field<String> field10() {
        return ExposureFunction.EXPOSURE_FUNCTION.FUNCTION_TEXT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getExposureDatasetId();
    }

    @Override
    public String component3() {
        return getPopulationGroup();
    }

    @Override
    public Integer component4() {
        return getRaceId();
    }

    @Override
    public Integer component5() {
        return getEthnicityId();
    }

    @Override
    public Integer component6() {
        return getGenderId();
    }

    @Override
    public Integer component7() {
        return getStartAge();
    }

    @Override
    public Integer component8() {
        return getEndAge();
    }

    @Override
    public Integer component9() {
        return getVariableId();
    }

    @Override
    public String component10() {
        return getFunctionText();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getExposureDatasetId();
    }

    @Override
    public String value3() {
        return getPopulationGroup();
    }

    @Override
    public Integer value4() {
        return getRaceId();
    }

    @Override
    public Integer value5() {
        return getEthnicityId();
    }

    @Override
    public Integer value6() {
        return getGenderId();
    }

    @Override
    public Integer value7() {
        return getStartAge();
    }

    @Override
    public Integer value8() {
        return getEndAge();
    }

    @Override
    public Integer value9() {
        return getVariableId();
    }

    @Override
    public String value10() {
        return getFunctionText();
    }

    @Override
    public ExposureFunctionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value2(Integer value) {
        setExposureDatasetId(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value3(String value) {
        setPopulationGroup(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value4(Integer value) {
        setRaceId(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value5(Integer value) {
        setEthnicityId(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value6(Integer value) {
        setGenderId(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value7(Integer value) {
        setStartAge(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value8(Integer value) {
        setEndAge(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value9(Integer value) {
        setVariableId(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord value10(String value) {
        setFunctionText(value);
        return this;
    }

    @Override
    public ExposureFunctionRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExposureFunctionRecord
     */
    public ExposureFunctionRecord() {
        super(ExposureFunction.EXPOSURE_FUNCTION);
    }

    /**
     * Create a detached, initialised ExposureFunctionRecord
     */
    public ExposureFunctionRecord(Integer id, Integer exposureDatasetId, String populationGroup, Integer raceId, Integer ethnicityId, Integer genderId, Integer startAge, Integer endAge, Integer variableId, String functionText) {
        super(ExposureFunction.EXPOSURE_FUNCTION);

        setId(id);
        setExposureDatasetId(exposureDatasetId);
        setPopulationGroup(populationGroup);
        setRaceId(raceId);
        setEthnicityId(ethnicityId);
        setGenderId(genderId);
        setStartAge(startAge);
        setEndAge(endAge);
        setVariableId(variableId);
        setFunctionText(functionText);
    }
}
