/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.GetExposureResults;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetExposureResultsRecord extends TableRecordImpl<GetExposureResultsRecord> implements Record10<Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.get_exposure_results.grid_col</code>.
     */
    public void setGridCol(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.grid_col</code>.
     */
    public Integer getGridCol() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.get_exposure_results.grid_row</code>.
     */
    public void setGridRow(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.grid_row</code>.
     */
    public Integer getGridRow() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.get_exposure_results.exposure_function_id</code>.
     */
    public void setExposureFunctionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.exposure_function_id</code>.
     */
    public Integer getExposureFunctionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>data.get_exposure_results.exposure_function_instance_id</code>.
     */
    public void setExposureFunctionInstanceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>data.get_exposure_results.exposure_function_instance_id</code>.
     */
    public Integer getExposureFunctionInstanceId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.get_exposure_results.result</code>.
     */
    public void setResult(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.result</code>.
     */
    public Double getResult() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>data.get_exposure_results.subgroup_population</code>.
     */
    public void setSubgroupPopulation(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.subgroup_population</code>.
     */
    public Double getSubgroupPopulation() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>data.get_exposure_results.all_population</code>.
     */
    public void setAllPopulation(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.all_population</code>.
     */
    public Double getAllPopulation() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>data.get_exposure_results.baseline_aq</code>.
     */
    public void setBaselineAq(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.baseline_aq</code>.
     */
    public Double getBaselineAq() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>data.get_exposure_results.scenario_aq</code>.
     */
    public void setScenarioAq(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.scenario_aq</code>.
     */
    public Double getScenarioAq() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>data.get_exposure_results.delta_aq</code>.
     */
    public void setDeltaAq(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>data.get_exposure_results.delta_aq</code>.
     */
    public Double getDeltaAq() {
        return (Double) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, Integer, Double, Double, Double, Double, Double, Double> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.GRID_COL;
    }

    @Override
    public Field<Integer> field2() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.GRID_ROW;
    }

    @Override
    public Field<Integer> field3() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.EXPOSURE_FUNCTION_ID;
    }

    @Override
    public Field<Integer> field4() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.EXPOSURE_FUNCTION_INSTANCE_ID;
    }

    @Override
    public Field<Double> field5() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.RESULT;
    }

    @Override
    public Field<Double> field6() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.SUBGROUP_POPULATION;
    }

    @Override
    public Field<Double> field7() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.ALL_POPULATION;
    }

    @Override
    public Field<Double> field8() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.BASELINE_AQ;
    }

    @Override
    public Field<Double> field9() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.SCENARIO_AQ;
    }

    @Override
    public Field<Double> field10() {
        return GetExposureResults.GET_EXPOSURE_RESULTS.DELTA_AQ;
    }

    @Override
    public Integer component1() {
        return getGridCol();
    }

    @Override
    public Integer component2() {
        return getGridRow();
    }

    @Override
    public Integer component3() {
        return getExposureFunctionId();
    }

    @Override
    public Integer component4() {
        return getExposureFunctionInstanceId();
    }

    @Override
    public Double component5() {
        return getResult();
    }

    @Override
    public Double component6() {
        return getSubgroupPopulation();
    }

    @Override
    public Double component7() {
        return getAllPopulation();
    }

    @Override
    public Double component8() {
        return getBaselineAq();
    }

    @Override
    public Double component9() {
        return getScenarioAq();
    }

    @Override
    public Double component10() {
        return getDeltaAq();
    }

    @Override
    public Integer value1() {
        return getGridCol();
    }

    @Override
    public Integer value2() {
        return getGridRow();
    }

    @Override
    public Integer value3() {
        return getExposureFunctionId();
    }

    @Override
    public Integer value4() {
        return getExposureFunctionInstanceId();
    }

    @Override
    public Double value5() {
        return getResult();
    }

    @Override
    public Double value6() {
        return getSubgroupPopulation();
    }

    @Override
    public Double value7() {
        return getAllPopulation();
    }

    @Override
    public Double value8() {
        return getBaselineAq();
    }

    @Override
    public Double value9() {
        return getScenarioAq();
    }

    @Override
    public Double value10() {
        return getDeltaAq();
    }

    @Override
    public GetExposureResultsRecord value1(Integer value) {
        setGridCol(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value2(Integer value) {
        setGridRow(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value3(Integer value) {
        setExposureFunctionId(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value4(Integer value) {
        setExposureFunctionInstanceId(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value5(Double value) {
        setResult(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value6(Double value) {
        setSubgroupPopulation(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value7(Double value) {
        setAllPopulation(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value8(Double value) {
        setBaselineAq(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value9(Double value) {
        setScenarioAq(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord value10(Double value) {
        setDeltaAq(value);
        return this;
    }

    @Override
    public GetExposureResultsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Double value5, Double value6, Double value7, Double value8, Double value9, Double value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetExposureResultsRecord
     */
    public GetExposureResultsRecord() {
        super(GetExposureResults.GET_EXPOSURE_RESULTS);
    }

    /**
     * Create a detached, initialised GetExposureResultsRecord
     */
    public GetExposureResultsRecord(Integer gridCol, Integer gridRow, Integer exposureFunctionId, Integer exposureFunctionInstanceId, Double result, Double subgroupPopulation, Double allPopulation, Double baselineAq, Double scenarioAq, Double deltaAq) {
        super(GetExposureResults.GET_EXPOSURE_RESULTS);

        setGridCol(gridCol);
        setGridRow(gridRow);
        setExposureFunctionId(exposureFunctionId);
        setExposureFunctionInstanceId(exposureFunctionInstanceId);
        setResult(result);
        setSubgroupPopulation(subgroupPopulation);
        setAllPopulation(allPopulation);
        setBaselineAq(baselineAq);
        setScenarioAq(scenarioAq);
        setDeltaAq(deltaAq);
    }
}
