/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.TPopDatasetYear;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPopDatasetYearRecord extends TableRecordImpl<TPopDatasetYearRecord> implements Record2<Integer, Short> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.t_pop_dataset_year.pop_dataset_id</code>.
     */
    public void setPopDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.t_pop_dataset_year.pop_dataset_id</code>.
     */
    public Integer getPopDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.t_pop_dataset_year.pop_year</code>.
     */
    public void setPopYear(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.t_pop_dataset_year.pop_year</code>.
     */
    public Short getPopYear() {
        return (Short) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Short> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Short> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TPopDatasetYear.T_POP_DATASET_YEAR.POP_DATASET_ID;
    }

    @Override
    public Field<Short> field2() {
        return TPopDatasetYear.T_POP_DATASET_YEAR.POP_YEAR;
    }

    @Override
    public Integer component1() {
        return getPopDatasetId();
    }

    @Override
    public Short component2() {
        return getPopYear();
    }

    @Override
    public Integer value1() {
        return getPopDatasetId();
    }

    @Override
    public Short value2() {
        return getPopYear();
    }

    @Override
    public TPopDatasetYearRecord value1(Integer value) {
        setPopDatasetId(value);
        return this;
    }

    @Override
    public TPopDatasetYearRecord value2(Short value) {
        setPopYear(value);
        return this;
    }

    @Override
    public TPopDatasetYearRecord values(Integer value1, Short value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPopDatasetYearRecord
     */
    public TPopDatasetYearRecord() {
        super(TPopDatasetYear.T_POP_DATASET_YEAR);
    }

    /**
     * Create a detached, initialised TPopDatasetYearRecord
     */
    public TPopDatasetYearRecord(Integer popDatasetId, Short popYear) {
        super(TPopDatasetYear.T_POP_DATASET_YEAR);

        setPopDatasetId(popDatasetId);
        setPopYear(popYear);
    }
}
