/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.ValuationResultFunctionConfig;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValuationResultFunctionConfigRecord extends TableRecordImpl<ValuationResultFunctionConfigRecord> implements Record5<Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>data.valuation_result_function_config.valuation_result_dataset_id</code>.
     */
    public void setValuationResultDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>data.valuation_result_function_config.valuation_result_dataset_id</code>.
     */
    public Integer getValuationResultDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.valuation_result_function_config.vf_id</code>.
     */
    public void setVfId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.valuation_result_function_config.vf_id</code>.
     */
    public Integer getVfId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.valuation_result_function_config.hif_id</code>.
     */
    public void setHifId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.valuation_result_function_config.hif_id</code>.
     */
    public Integer getHifId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>data.valuation_result_function_config.hif_instance_id</code>.
     */
    public void setHifInstanceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>data.valuation_result_function_config.hif_instance_id</code>.
     */
    public Integer getHifInstanceId() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>data.valuation_result_function_config.vf_instance_id</code>.
     */
    public void setVfInstanceId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>data.valuation_result_function_config.vf_instance_id</code>.
     */
    public Integer getVfInstanceId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ValuationResultFunctionConfig.VALUATION_RESULT_FUNCTION_CONFIG.VALUATION_RESULT_DATASET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ValuationResultFunctionConfig.VALUATION_RESULT_FUNCTION_CONFIG.VF_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ValuationResultFunctionConfig.VALUATION_RESULT_FUNCTION_CONFIG.HIF_ID;
    }

    @Override
    public Field<Integer> field4() {
        return ValuationResultFunctionConfig.VALUATION_RESULT_FUNCTION_CONFIG.HIF_INSTANCE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return ValuationResultFunctionConfig.VALUATION_RESULT_FUNCTION_CONFIG.VF_INSTANCE_ID;
    }

    @Override
    public Integer component1() {
        return getValuationResultDatasetId();
    }

    @Override
    public Integer component2() {
        return getVfId();
    }

    @Override
    public Integer component3() {
        return getHifId();
    }

    @Override
    public Integer component4() {
        return getHifInstanceId();
    }

    @Override
    public Integer component5() {
        return getVfInstanceId();
    }

    @Override
    public Integer value1() {
        return getValuationResultDatasetId();
    }

    @Override
    public Integer value2() {
        return getVfId();
    }

    @Override
    public Integer value3() {
        return getHifId();
    }

    @Override
    public Integer value4() {
        return getHifInstanceId();
    }

    @Override
    public Integer value5() {
        return getVfInstanceId();
    }

    @Override
    public ValuationResultFunctionConfigRecord value1(Integer value) {
        setValuationResultDatasetId(value);
        return this;
    }

    @Override
    public ValuationResultFunctionConfigRecord value2(Integer value) {
        setVfId(value);
        return this;
    }

    @Override
    public ValuationResultFunctionConfigRecord value3(Integer value) {
        setHifId(value);
        return this;
    }

    @Override
    public ValuationResultFunctionConfigRecord value4(Integer value) {
        setHifInstanceId(value);
        return this;
    }

    @Override
    public ValuationResultFunctionConfigRecord value5(Integer value) {
        setVfInstanceId(value);
        return this;
    }

    @Override
    public ValuationResultFunctionConfigRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ValuationResultFunctionConfigRecord
     */
    public ValuationResultFunctionConfigRecord() {
        super(ValuationResultFunctionConfig.VALUATION_RESULT_FUNCTION_CONFIG);
    }

    /**
     * Create a detached, initialised ValuationResultFunctionConfigRecord
     */
    public ValuationResultFunctionConfigRecord(Integer valuationResultDatasetId, Integer vfId, Integer hifId, Integer hifInstanceId, Integer vfInstanceId) {
        super(ValuationResultFunctionConfig.VALUATION_RESULT_FUNCTION_CONFIG);

        setValuationResultDatasetId(valuationResultDatasetId);
        setVfId(vfId);
        setHifId(hifId);
        setHifInstanceId(hifInstanceId);
        setVfInstanceId(vfInstanceId);
    }
}
