/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.ValuationFunction;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValuationFunctionRecord extends UpdatableRecordImpl<ValuationFunctionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.valuation_function.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.valuation_function.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.valuation_function.valuation_dataset_id</code>.
     */
    public void setValuationDatasetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.valuation_function.valuation_dataset_id</code>.
     */
    public Integer getValuationDatasetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.valuation_function.endpoint_group_id</code>.
     */
    public void setEndpointGroupId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.valuation_function.endpoint_group_id</code>.
     */
    public Integer getEndpointGroupId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>data.valuation_function.endpoint_id</code>.
     */
    public void setEndpointId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.valuation_function.endpoint_id</code>.
     */
    public Integer getEndpointId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.valuation_function.qualifier</code>.
     */
    public void setQualifier_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.valuation_function.qualifier</code>.
     */
    public String getQualifier_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>data.valuation_function.reference</code>.
     */
    public void setReference(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.valuation_function.reference</code>.
     */
    public String getReference() {
        return (String) get(5);
    }

    /**
     * Setter for <code>data.valuation_function.start_age</code>.
     */
    public void setStartAge(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.valuation_function.start_age</code>.
     */
    public Integer getStartAge() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>data.valuation_function.end_age</code>.
     */
    public void setEndAge(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.valuation_function.end_age</code>.
     */
    public Integer getEndAge() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>data.valuation_function.function_text</code>.
     */
    public void setFunctionText(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>data.valuation_function.function_text</code>.
     */
    public String getFunctionText() {
        return (String) get(8);
    }

    /**
     * Setter for <code>data.valuation_function.val_a</code>.
     */
    public void setValA(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_a</code>.
     */
    public Double getValA() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>data.valuation_function.name_a</code>.
     */
    public void setNameA(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>data.valuation_function.name_a</code>.
     */
    public String getNameA() {
        return (String) get(10);
    }

    /**
     * Setter for <code>data.valuation_function.dist_a</code>.
     */
    public void setDistA(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>data.valuation_function.dist_a</code>.
     */
    public String getDistA() {
        return (String) get(11);
    }

    /**
     * Setter for <code>data.valuation_function.p1a</code>.
     */
    public void setP1a(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>data.valuation_function.p1a</code>.
     */
    public Double getP1a() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>data.valuation_function.p2a</code>.
     */
    public void setP2a(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>data.valuation_function.p2a</code>.
     */
    public Double getP2a() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>data.valuation_function.val_b</code>.
     */
    public void setValB(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_b</code>.
     */
    public Double getValB() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>data.valuation_function.name_b</code>.
     */
    public void setNameB(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>data.valuation_function.name_b</code>.
     */
    public String getNameB() {
        return (String) get(15);
    }

    /**
     * Setter for <code>data.valuation_function.val_c</code>.
     */
    public void setValC(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_c</code>.
     */
    public Double getValC() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>data.valuation_function.name_c</code>.
     */
    public void setNameC(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>data.valuation_function.name_c</code>.
     */
    public String getNameC() {
        return (String) get(17);
    }

    /**
     * Setter for <code>data.valuation_function.val_d</code>.
     */
    public void setValD(Double value) {
        set(18, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_d</code>.
     */
    public Double getValD() {
        return (Double) get(18);
    }

    /**
     * Setter for <code>data.valuation_function.name_d</code>.
     */
    public void setNameD(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>data.valuation_function.name_d</code>.
     */
    public String getNameD() {
        return (String) get(19);
    }

    /**
     * Setter for <code>data.valuation_function.epa_standard</code>.
     */
    public void setEpaStandard(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>data.valuation_function.epa_standard</code>.
     */
    public Boolean getEpaStandard() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>data.valuation_function.val_a_array</code>.
     */
    public void setValAArray(Double[] value) {
        set(21, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_a_array</code>.
     */
    public Double[] getValAArray() {
        return (Double[]) get(21);
    }

    /**
     * Setter for <code>data.valuation_function.val_b_array</code>.
     */
    public void setValBArray(Double[] value) {
        set(22, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_b_array</code>.
     */
    public Double[] getValBArray() {
        return (Double[]) get(22);
    }

    /**
     * Setter for <code>data.valuation_function.val_c_array</code>.
     */
    public void setValCArray(Double[] value) {
        set(23, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_c_array</code>.
     */
    public Double[] getValCArray() {
        return (Double[]) get(23);
    }

    /**
     * Setter for <code>data.valuation_function.val_d_array</code>.
     */
    public void setValDArray(Double[] value) {
        set(24, value);
    }

    /**
     * Getter for <code>data.valuation_function.val_d_array</code>.
     */
    public Double[] getValDArray() {
        return (Double[]) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ValuationFunctionRecord
     */
    public ValuationFunctionRecord() {
        super(ValuationFunction.VALUATION_FUNCTION);
    }

    /**
     * Create a detached, initialised ValuationFunctionRecord
     */
    public ValuationFunctionRecord(Integer id, Integer valuationDatasetId, Integer endpointGroupId, Integer endpointId, String qualifier, String reference, Integer startAge, Integer endAge, String functionText, Double valA, String nameA, String distA, Double p1a, Double p2a, Double valB, String nameB, Double valC, String nameC, Double valD, String nameD, Boolean epaStandard, Double[] valAArray, Double[] valBArray, Double[] valCArray, Double[] valDArray) {
        super(ValuationFunction.VALUATION_FUNCTION);

        setId(id);
        setValuationDatasetId(valuationDatasetId);
        setEndpointGroupId(endpointGroupId);
        setEndpointId(endpointId);
        setQualifier_(qualifier);
        setReference(reference);
        setStartAge(startAge);
        setEndAge(endAge);
        setFunctionText(functionText);
        setValA(valA);
        setNameA(nameA);
        setDistA(distA);
        setP1a(p1a);
        setP2a(p2a);
        setValB(valB);
        setNameB(nameB);
        setValC(valC);
        setNameC(nameC);
        setValD(valD);
        setNameD(nameD);
        setEpaStandard(epaStandard);
        setValAArray(valAArray);
        setValBArray(valBArray);
        setValCArray(valCArray);
        setValDArray(valDArray);
    }
}
