apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bencloud-server-pv-claim
  namespace: benmap-stg
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: bencloud-server-pv
  resources:
    requests:
      storage: 5Gi