/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables.records;


import gov.epa.bencloud.server.database.jooq.grids.tables.UsaCtGridsDissolve;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsaCtGridsDissolveRecord extends UpdatableRecordImpl<UsaCtGridsDissolveRecord> implements Record4<Integer, BigDecimal, BigDecimal, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>grids.usa_ct_grids_dissolve.gid</code>.
     */
    public void setGid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>grids.usa_ct_grids_dissolve.gid</code>.
     */
    public Integer getGid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>grids.usa_ct_grids_dissolve.row</code>.
     */
    public void setRow(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>grids.usa_ct_grids_dissolve.row</code>.
     */
    public BigDecimal getRow() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>grids.usa_ct_grids_dissolve.col</code>.
     */
    public void setCol(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>grids.usa_ct_grids_dissolve.col</code>.
     */
    public BigDecimal getCol() {
        return (BigDecimal) get(2);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public void setGeom(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public Object getGeom() {
        return get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, BigDecimal, BigDecimal, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, BigDecimal, BigDecimal, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UsaCtGridsDissolve.USA_CT_GRIDS_DISSOLVE.GID;
    }

    @Override
    public Field<BigDecimal> field2() {
        return UsaCtGridsDissolve.USA_CT_GRIDS_DISSOLVE.ROW;
    }

    @Override
    public Field<BigDecimal> field3() {
        return UsaCtGridsDissolve.USA_CT_GRIDS_DISSOLVE.COL;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return UsaCtGridsDissolve.USA_CT_GRIDS_DISSOLVE.GEOM;
    }

    @Override
    public Integer component1() {
        return getGid();
    }

    @Override
    public BigDecimal component2() {
        return getRow();
    }

    @Override
    public BigDecimal component3() {
        return getCol();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getGeom();
    }

    @Override
    public Integer value1() {
        return getGid();
    }

    @Override
    public BigDecimal value2() {
        return getRow();
    }

    @Override
    public BigDecimal value3() {
        return getCol();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getGeom();
    }

    @Override
    public UsaCtGridsDissolveRecord value1(Integer value) {
        setGid(value);
        return this;
    }

    @Override
    public UsaCtGridsDissolveRecord value2(BigDecimal value) {
        setRow(value);
        return this;
    }

    @Override
    public UsaCtGridsDissolveRecord value3(BigDecimal value) {
        setCol(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public UsaCtGridsDissolveRecord value4(Object value) {
        setGeom(value);
        return this;
    }

    @Override
    public UsaCtGridsDissolveRecord values(Integer value1, BigDecimal value2, BigDecimal value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsaCtGridsDissolveRecord
     */
    public UsaCtGridsDissolveRecord() {
        super(UsaCtGridsDissolve.USA_CT_GRIDS_DISSOLVE);
    }

    /**
     * Create a detached, initialised UsaCtGridsDissolveRecord
     */
    public UsaCtGridsDissolveRecord(Integer gid, BigDecimal row, BigDecimal col, Object geom) {
        super(UsaCtGridsDissolve.USA_CT_GRIDS_DISSOLVE);

        setGid(gid);
        setRow(row);
        setCol(col);
        setGeom(geom);
    }
}
