/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables.records;


import gov.epa.bencloud.server.database.jooq.grids.tables.UsCounty_2020;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsCounty_2020Record extends UpdatableRecordImpl<UsCounty_2020Record> implements Record21<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Double, Double, String, String, Integer, Integer, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>grids.us_county_2020.gid</code>.
     */
    public void setGid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.gid</code>.
     */
    public Integer getGid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>grids.us_county_2020.statefp</code>.
     */
    public void setStatefp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.statefp</code>.
     */
    public String getStatefp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>grids.us_county_2020.countyfp</code>.
     */
    public void setCountyfp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.countyfp</code>.
     */
    public String getCountyfp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>grids.us_county_2020.countyns</code>.
     */
    public void setCountyns(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.countyns</code>.
     */
    public String getCountyns() {
        return (String) get(3);
    }

    /**
     * Setter for <code>grids.us_county_2020.geoid</code>.
     */
    public void setGeoid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.geoid</code>.
     */
    public String getGeoid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>grids.us_county_2020.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>grids.us_county_2020.namelsad</code>.
     */
    public void setNamelsad(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.namelsad</code>.
     */
    public String getNamelsad() {
        return (String) get(6);
    }

    /**
     * Setter for <code>grids.us_county_2020.lsad</code>.
     */
    public void setLsad(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.lsad</code>.
     */
    public String getLsad() {
        return (String) get(7);
    }

    /**
     * Setter for <code>grids.us_county_2020.classfp</code>.
     */
    public void setClassfp(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.classfp</code>.
     */
    public String getClassfp() {
        return (String) get(8);
    }

    /**
     * Setter for <code>grids.us_county_2020.mtfcc</code>.
     */
    public void setMtfcc(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.mtfcc</code>.
     */
    public String getMtfcc() {
        return (String) get(9);
    }

    /**
     * Setter for <code>grids.us_county_2020.csafp</code>.
     */
    public void setCsafp(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.csafp</code>.
     */
    public String getCsafp() {
        return (String) get(10);
    }

    /**
     * Setter for <code>grids.us_county_2020.cbsafp</code>.
     */
    public void setCbsafp(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.cbsafp</code>.
     */
    public String getCbsafp() {
        return (String) get(11);
    }

    /**
     * Setter for <code>grids.us_county_2020.metdivfp</code>.
     */
    public void setMetdivfp(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.metdivfp</code>.
     */
    public String getMetdivfp() {
        return (String) get(12);
    }

    /**
     * Setter for <code>grids.us_county_2020.funcstat</code>.
     */
    public void setFuncstat(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.funcstat</code>.
     */
    public String getFuncstat() {
        return (String) get(13);
    }

    /**
     * Setter for <code>grids.us_county_2020.aland</code>.
     */
    public void setAland(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.aland</code>.
     */
    public Double getAland() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>grids.us_county_2020.awater</code>.
     */
    public void setAwater(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.awater</code>.
     */
    public Double getAwater() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>grids.us_county_2020.intptlat</code>.
     */
    public void setIntptlat(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.intptlat</code>.
     */
    public String getIntptlat() {
        return (String) get(16);
    }

    /**
     * Setter for <code>grids.us_county_2020.intptlon</code>.
     */
    public void setIntptlon(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.intptlon</code>.
     */
    public String getIntptlon() {
        return (String) get(17);
    }

    /**
     * Setter for <code>grids.us_county_2020.col</code>.
     */
    public void setCol(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.col</code>.
     */
    public Integer getCol() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>grids.us_county_2020.row</code>.
     */
    public void setRow(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>grids.us_county_2020.row</code>.
     */
    public Integer getRow() {
        return (Integer) get(19);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public void setGeom(Object value) {
        set(20, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public Object getGeom() {
        return get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Double, Double, String, String, Integer, Integer, Object> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Double, Double, String, String, Integer, Integer, Object> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UsCounty_2020.US_COUNTY_2020.GID;
    }

    @Override
    public Field<String> field2() {
        return UsCounty_2020.US_COUNTY_2020.STATEFP;
    }

    @Override
    public Field<String> field3() {
        return UsCounty_2020.US_COUNTY_2020.COUNTYFP;
    }

    @Override
    public Field<String> field4() {
        return UsCounty_2020.US_COUNTY_2020.COUNTYNS;
    }

    @Override
    public Field<String> field5() {
        return UsCounty_2020.US_COUNTY_2020.GEOID;
    }

    @Override
    public Field<String> field6() {
        return UsCounty_2020.US_COUNTY_2020.NAME;
    }

    @Override
    public Field<String> field7() {
        return UsCounty_2020.US_COUNTY_2020.NAMELSAD;
    }

    @Override
    public Field<String> field8() {
        return UsCounty_2020.US_COUNTY_2020.LSAD;
    }

    @Override
    public Field<String> field9() {
        return UsCounty_2020.US_COUNTY_2020.CLASSFP;
    }

    @Override
    public Field<String> field10() {
        return UsCounty_2020.US_COUNTY_2020.MTFCC;
    }

    @Override
    public Field<String> field11() {
        return UsCounty_2020.US_COUNTY_2020.CSAFP;
    }

    @Override
    public Field<String> field12() {
        return UsCounty_2020.US_COUNTY_2020.CBSAFP;
    }

    @Override
    public Field<String> field13() {
        return UsCounty_2020.US_COUNTY_2020.METDIVFP;
    }

    @Override
    public Field<String> field14() {
        return UsCounty_2020.US_COUNTY_2020.FUNCSTAT;
    }

    @Override
    public Field<Double> field15() {
        return UsCounty_2020.US_COUNTY_2020.ALAND;
    }

    @Override
    public Field<Double> field16() {
        return UsCounty_2020.US_COUNTY_2020.AWATER;
    }

    @Override
    public Field<String> field17() {
        return UsCounty_2020.US_COUNTY_2020.INTPTLAT;
    }

    @Override
    public Field<String> field18() {
        return UsCounty_2020.US_COUNTY_2020.INTPTLON;
    }

    @Override
    public Field<Integer> field19() {
        return UsCounty_2020.US_COUNTY_2020.COL;
    }

    @Override
    public Field<Integer> field20() {
        return UsCounty_2020.US_COUNTY_2020.ROW;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field21() {
        return UsCounty_2020.US_COUNTY_2020.GEOM;
    }

    @Override
    public Integer component1() {
        return getGid();
    }

    @Override
    public String component2() {
        return getStatefp();
    }

    @Override
    public String component3() {
        return getCountyfp();
    }

    @Override
    public String component4() {
        return getCountyns();
    }

    @Override
    public String component5() {
        return getGeoid();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getNamelsad();
    }

    @Override
    public String component8() {
        return getLsad();
    }

    @Override
    public String component9() {
        return getClassfp();
    }

    @Override
    public String component10() {
        return getMtfcc();
    }

    @Override
    public String component11() {
        return getCsafp();
    }

    @Override
    public String component12() {
        return getCbsafp();
    }

    @Override
    public String component13() {
        return getMetdivfp();
    }

    @Override
    public String component14() {
        return getFuncstat();
    }

    @Override
    public Double component15() {
        return getAland();
    }

    @Override
    public Double component16() {
        return getAwater();
    }

    @Override
    public String component17() {
        return getIntptlat();
    }

    @Override
    public String component18() {
        return getIntptlon();
    }

    @Override
    public Integer component19() {
        return getCol();
    }

    @Override
    public Integer component20() {
        return getRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Object component21() {
        return getGeom();
    }

    @Override
    public Integer value1() {
        return getGid();
    }

    @Override
    public String value2() {
        return getStatefp();
    }

    @Override
    public String value3() {
        return getCountyfp();
    }

    @Override
    public String value4() {
        return getCountyns();
    }

    @Override
    public String value5() {
        return getGeoid();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getNamelsad();
    }

    @Override
    public String value8() {
        return getLsad();
    }

    @Override
    public String value9() {
        return getClassfp();
    }

    @Override
    public String value10() {
        return getMtfcc();
    }

    @Override
    public String value11() {
        return getCsafp();
    }

    @Override
    public String value12() {
        return getCbsafp();
    }

    @Override
    public String value13() {
        return getMetdivfp();
    }

    @Override
    public String value14() {
        return getFuncstat();
    }

    @Override
    public Double value15() {
        return getAland();
    }

    @Override
    public Double value16() {
        return getAwater();
    }

    @Override
    public String value17() {
        return getIntptlat();
    }

    @Override
    public String value18() {
        return getIntptlon();
    }

    @Override
    public Integer value19() {
        return getCol();
    }

    @Override
    public Integer value20() {
        return getRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Object value21() {
        return getGeom();
    }

    @Override
    public UsCounty_2020Record value1(Integer value) {
        setGid(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value2(String value) {
        setStatefp(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value3(String value) {
        setCountyfp(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value4(String value) {
        setCountyns(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value5(String value) {
        setGeoid(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value7(String value) {
        setNamelsad(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value8(String value) {
        setLsad(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value9(String value) {
        setClassfp(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value10(String value) {
        setMtfcc(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value11(String value) {
        setCsafp(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value12(String value) {
        setCbsafp(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value13(String value) {
        setMetdivfp(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value14(String value) {
        setFuncstat(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value15(Double value) {
        setAland(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value16(Double value) {
        setAwater(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value17(String value) {
        setIntptlat(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value18(String value) {
        setIntptlon(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value19(Integer value) {
        setCol(value);
        return this;
    }

    @Override
    public UsCounty_2020Record value20(Integer value) {
        setRow(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public UsCounty_2020Record value21(Object value) {
        setGeom(value);
        return this;
    }

    @Override
    public UsCounty_2020Record values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, Double value15, Double value16, String value17, String value18, Integer value19, Integer value20, Object value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsCounty_2020Record
     */
    public UsCounty_2020Record() {
        super(UsCounty_2020.US_COUNTY_2020);
    }

    /**
     * Create a detached, initialised UsCounty_2020Record
     */
    public UsCounty_2020Record(Integer gid, String statefp, String countyfp, String countyns, String geoid, String name, String namelsad, String lsad, String classfp, String mtfcc, String csafp, String cbsafp, String metdivfp, String funcstat, Double aland, Double awater, String intptlat, String intptlon, Integer col, Integer row, Object geom) {
        super(UsCounty_2020.US_COUNTY_2020);

        setGid(gid);
        setStatefp(statefp);
        setCountyfp(countyfp);
        setCountyns(countyns);
        setGeoid(geoid);
        setName(name);
        setNamelsad(namelsad);
        setLsad(lsad);
        setClassfp(classfp);
        setMtfcc(mtfcc);
        setCsafp(csafp);
        setCbsafp(cbsafp);
        setMetdivfp(metdivfp);
        setFuncstat(funcstat);
        setAland(aland);
        setAwater(awater);
        setIntptlat(intptlat);
        setIntptlon(intptlon);
        setCol(col);
        setRow(row);
        setGeom(geom);
    }
}
