/**** Update HI Katsouyanni's functions.****/

UPDATE "data".settings SET value_int=43 WHERE "key"='version';

DELETE FROM "data".health_impact_function WHERE author = 'Katsouyanni et al.' AND health_impact_function_dataset_id = 15;

INSERT INTO "data".health_impact_function (id,health_impact_function_dataset_id,endpoint_group_id,endpoint_id,pollutant_id,metric_id,seasonal_metric_id,metric_statistic,author,function_year,"location",other_pollutants,qualifier,reference,start_age,end_age,function_text,incidence_dataset_id,prevalence_dataset_id,variable_dataset_id,beta,dist_beta,p1_beta,p2_beta,val_a,name_a,val_b,name_b,val_c,name_c,baseline_function_text,race_id,gender_id,ethnicity_id,start_day,end_day) VALUES
	 (1024,15,10,22,4,6,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Warm Season (April - September). Average of Lags 0-1 day; Penalized splines (Table 40)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',65,99,'(1-(1/exp(BETA*DELTAQ)))*INCIDENCE*POPULATION',NULL,NULL,NULL,0.000548493,'Normal',0.000345081,0.0,0.0,NULL,0.0,NULL,0.0,NULL,'INCIDENCE*POPULATION',5,3,3,120,272),
	 (1032,15,12,50,4,6,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Sensitivity Analysis: At-risk factor age (Ages 0-74), Warm Season (April-September), Distributed Lags, Penalized splines, Table 24','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,74,'(1-(1/((1-INCIDENCE)*exp(BETA*DELTAQ)+INCIDENCE)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.0013607,'Normal',0.000415218,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',0.0,NULL,0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1033,15,12,50,4,6,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Sensitivity Analysis: At-risk factor age (older adults), Warm Season (April-September), Distributed Lags, Penalized splines, Table 24','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',75,99,'(1-(1/((1-INCIDENCE)*exp(BETA*DELTAQ)+INCIDENCE)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001212618,'Normal',0.000456204,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',0.0,NULL,0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1027,15,12,56,4,6,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Sensitivity Analysis: Warm Season (April - September). Lag 1; Penalized splines; O3 Results (Table 24)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,99,'(1-(1/exp(BETA*DELTAQ)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001498713,'Normal',0.000593112,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',0.0,NULL,0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1026,15,12,56,4,6,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities','PM10','Sensitivity Analysis: Warm Season (April - September). Lag 1; Penalized splines; Controlling for PM10 (Table 24)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,99,'(1-(1/exp(BETA*DELTAQ)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001921422,'Normal',0.00129656,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',0.0,NULL,0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1025,15,12,56,4,6,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Warm Season (April - September). Distributed Lags; Penalized splines; O3 Results (Table 24)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,99,'(1-(1/exp(BETA*DELTAQ)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001419872,'Normal',0.001106798,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',0.0,NULL,0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1028,15,10,22,4,8,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Warm Season (April - September). Average of Lags 0-1 day; Penalized splines (Table 40)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',65,99,'(1-(1/exp(BETA*A*DELTAQ)))*INCIDENCE*POPULATION',NULL,NULL,NULL,0.000548493,'Normal',0.000345081,0.0,1.13,'Mean summer ratio of 1 hr max to 8 hr max ozone; 78 communities 2000 - 2004 from Anderson and Bell 2008; used to scale beta value to 8-hr max exposure metric',0.0,NULL,0.0,NULL,'INCIDENCE*POPULATION',5,3,3,120,272),
	 (1034,15,12,50,4,8,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Sensitivity Analysis: At-risk factor age (Ages 0-74), Warm Season (April-September), Distributed Lags, Penalized splines, Table 24','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,74,'(1-(1/((1-INCIDENCE)*exp(BETA*B*DELTAQ)+INCIDENCE)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.0013607,'Normal',0.000415218,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',1.13,'Mean summer ratio of 1 hr max to 8 hr max ozone; 78 communities 2000 - 2004 from Anderson and Bell 2008; used to scale beta value to 8-hr max exposure metric',0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1035,15,12,50,4,8,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Sensitivity Analysis: At-risk factor age (older adults), Warm Season (April-September), Distributed Lags, Penalized splines, Table 24','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',75,99,'(1-(1/((1-INCIDENCE)*exp(BETA*B*DELTAQ)+INCIDENCE)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001212618,'Normal',0.000456204,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',1.13,'Mean summer ratio of 1 hr max to 8 hr max ozone; 78 communities 2000 - 2004 from Anderson and Bell 2008; used to scale beta value to 8-hr max exposure metric',0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1031,15,12,56,4,8,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Sensitivity Analysis: Warm Season (April - September). Lag 1; Penalized splines; O3 Results (Table 24)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,99,'(1-(1/exp(BETA*B*DELTAQ)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001498713,'Normal',0.000593112,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',1.13,'Mean summer ratio of 1 hr max to 8 hr max ozone; 78 communities 2000 - 2004 from Anderson and Bell 2008; used to scale beta value to 8-hr max exposure metric',0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1030,15,12,56,4,8,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities','PM10','Sensitivity Analysis: Warm Season (April - September). Lag 1; Penalized splines; Controlling for PM10 (Table 24)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,99,'(1-(1/exp(BETA*B*DELTAQ)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001921422,'Normal',0.00129656,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',1.13,'Mean summer ratio of 1 hr max to 8 hr max ozone; 78 communities 2000 - 2004 from Anderson and Bell 2008; used to scale beta value to 8-hr max exposure metric',0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272),
	 (1029,15,12,56,4,8,NULL,0,'Katsouyanni et al.',2009,'90 U.S. Cities',NULL,'Warm Season (April - September). Distributed Lags; Penalized splines; O3 Results (Table 24)','Katsouyanni, K., Samet, J.M., Anderson, H.R., Atkinson, R., Le Tertre, A., Medina, S., Samoli, E., Touloumi, G., Burnett, R.T., Krewski, D., Ramsay, T., Dominici, F., Peng, R.D., Schwartz, J., Zanobetti, A. 2009. Air pollution and health: A European and North American approach (APHENA). Health Effects Institute, 5-90.',0,99,'(1-(1/exp(BETA*B*DELTAQ)))*INCIDENCE*POPULATION*A',NULL,NULL,NULL,0.001419872,'Normal',0.001106798,0.0,0.002739726,'Scalar to convert annual mortality rate to daily rate',1.13,'Mean summer ratio of 1 hr max to 8 hr max ozone; 78 communities 2000 - 2004 from Anderson and Bell 2008; used to scale beta value to 8-hr max exposure metric',0.0,NULL,'INCIDENCE*POPULATION*A',5,3,3,120,272);

SELECT SETVAL('data.health_impact_function_id_seq', COALESCE(MAX(id), 1) ) FROM data.health_impact_function;

VACUUM (VERBOSE, ANALYZE) "data".health_impact_function;