/*BWD 255 Update Health Impact Function references and URLs (dementia function urls were updated when adding the functions) */

UPDATE "data".settings SET value_int=85 where "key"='version';

--Update valuation functions to update reference and URLs

UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 494;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 495;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 496;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 497;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 498;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 499;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 500;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.jeem.2003.12.005', reference = 'Dickie M., Messman V. (2004). Parental altruism and the value of avoiding acute illness: are kids worth more than parents? Journal of Environmental Economics and Management 48(3), 1146-1174.' WHERE id = 501;
UPDATE data.valuation_function SET access_url = 'https://pubmed.ncbi.nlm.nih.gov/9309994/', reference = 'Smith D.H., Malone D.C., Lawson K.A., Okamoto L.J., Battista C., Saunders W.B. (1997). A national estimate of the economic costs of asthma. American jounral of respiratory and critical care medicine, 156(3 Pt1), 787-793.' WHERE id = 503;
UPDATE data.valuation_function SET access_url = 'https://pubmed.ncbi.nlm.nih.gov/10390402/', reference = 'Stanford R., McLaughlin T., Okamoto L.J. (1999). The cost of asthma in the emergency department and hospital. American journal of respiratory and critical care medicine, 16091), 211-215. ' WHERE id = 504;
UPDATE data.valuation_function SET access_url = 'https://hcup-us.ahrq.gov/nedsoverview.jsp', reference = 'HCUP National Inpatient Sample (NIS). Healthcare Cost and Utilization Project (HCUP). 2007. Agency for Healthcare Research and Quality, Rockville, MD. www.hcup-us.ahrq.gov/nisoverview.jsp ' WHERE id = 509;
UPDATE data.valuation_function SET access_url = 'https://www3.epa.gov/ttnecas1/regdata/Benefits/background/neumannn1994.pdf', reference = 'Industrial Economics Incorporated (IEc). 1993. Memorandum to Jim DeMocker, U.S. Environmental Protection Agency, Office of Air and Radiation, Office of Policy Analysis and Review. September 30.' WHERE id = 541;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 542;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 543;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 544;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 545;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 546;
UPDATE data.valuation_function SET access_url = 'https://data.census.gov/table/ACSST5Y2021.B19301', reference = 'U.S. Bureau of the Census. 2022. Table B19301: Per Capita Income in the Past 12 Months, 2021 American Community Survey 5-Year Estimates' WHERE id = 547;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 558;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 559;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 579;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 580;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 581;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 582;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 583;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 584;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 585;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 586;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 587;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 588;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 589;
UPDATE data.valuation_function SET access_url = 'https://doi.org/10.1016/j.ecresq.2021.11.008', reference = 'Gottfried, M. and Ansari, A. 2022. Classrooms with high rates of absenteeism and individual success: Exploring students’ achievement, executive function, and socio-behavioral outcomes. Early Childhood Research Quarterly, 59: 215-227.' WHERE id = 590;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 592;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 593;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 594;
UPDATE data.valuation_function SET access_url = 'https://global.oup.com/academic/product/fatal-tradeoffs-9780195102932?cc=us&lang=en&', reference = 'Viscusi, K. (1992). Fatal Tradeoffs: Public and Private Responsibilities for Risk. Oxford University Press' WHERE id = 595;
