/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables;


import gov.epa.bencloud.server.database.jooq.data.Data;
import gov.epa.bencloud.server.database.jooq.data.Indexes;
import gov.epa.bencloud.server.database.jooq.data.Keys;
import gov.epa.bencloud.server.database.jooq.data.tables.records.PopulationGrowthB2010T2020Record;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PopulationGrowthB2010T2020 extends TableImpl<PopulationGrowthB2010T2020Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.population_growth_b2010_t2020</code>
     */
    public static final PopulationGrowthB2010T2020 POPULATION_GROWTH_B2010_T2020 = new PopulationGrowthB2010T2020();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PopulationGrowthB2010T2020Record> getRecordType() {
        return PopulationGrowthB2010T2020Record.class;
    }

    /**
     * The column <code>data.population_growth_b2010_t2020.base_pop_year</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Short> BASE_POP_YEAR = createField(DSL.name("base_pop_year"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>data.population_growth_b2010_t2020.pop_year</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Short> POP_YEAR = createField(DSL.name("pop_year"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>data.population_growth_b2010_t2020.race_id</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Integer> RACE_ID = createField(DSL.name("race_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>data.population_growth_b2010_t2020.gender_id</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Integer> GENDER_ID = createField(DSL.name("gender_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>data.population_growth_b2010_t2020.ethnicity_id</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Integer> ETHNICITY_ID = createField(DSL.name("ethnicity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>data.population_growth_b2010_t2020.age_range_id</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Integer> AGE_RANGE_ID = createField(DSL.name("age_range_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>data.population_growth_b2010_t2020.grid_cell_id</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Integer> GRID_CELL_ID = createField(DSL.name("grid_cell_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>data.population_growth_b2010_t2020.growth_value</code>.
     */
    public final TableField<PopulationGrowthB2010T2020Record, Double> GROWTH_VALUE = createField(DSL.name("growth_value"), SQLDataType.DOUBLE, this, "");

    private PopulationGrowthB2010T2020(Name alias, Table<PopulationGrowthB2010T2020Record> aliased) {
        this(alias, aliased, null);
    }

    private PopulationGrowthB2010T2020(Name alias, Table<PopulationGrowthB2010T2020Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.population_growth_b2010_t2020</code> table
     * reference
     */
    public PopulationGrowthB2010T2020(String alias) {
        this(DSL.name(alias), POPULATION_GROWTH_B2010_T2020);
    }

    /**
     * Create an aliased <code>data.population_growth_b2010_t2020</code> table
     * reference
     */
    public PopulationGrowthB2010T2020(Name alias) {
        this(alias, POPULATION_GROWTH_B2010_T2020);
    }

    /**
     * Create a <code>data.population_growth_b2010_t2020</code> table reference
     */
    public PopulationGrowthB2010T2020() {
        this(DSL.name("population_growth_b2010_t2020"), null);
    }

    public <O extends Record> PopulationGrowthB2010T2020(Table<O> child, ForeignKey<O, PopulationGrowthB2010T2020Record> key) {
        super(child, key, POPULATION_GROWTH_B2010_T2020);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Data.DATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.POPULATION_GROWTH_B2010_T2020_BASE_POP_YEAR_IDX, Indexes.POPULATION_GROWTH_B2010_T2020_RACE_ID_ETHNICITY_ID_GRID_CE_IDX1, Indexes.POPULATION_GROWTH_B2010_T2020_RACE_ID_ETHNICITY_ID_GRID_CEL_IDX);
    }

    @Override
    public UniqueKey<PopulationGrowthB2010T2020Record> getPrimaryKey() {
        return Keys.POPULATION_GROWTH_B2010_T2020_PKEY;
    }

    @Override
    public PopulationGrowthB2010T2020 as(String alias) {
        return new PopulationGrowthB2010T2020(DSL.name(alias), this);
    }

    @Override
    public PopulationGrowthB2010T2020 as(Name alias) {
        return new PopulationGrowthB2010T2020(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PopulationGrowthB2010T2020 rename(String name) {
        return new PopulationGrowthB2010T2020(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PopulationGrowthB2010T2020 rename(Name name) {
        return new PopulationGrowthB2010T2020(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Short, Short, Integer, Integer, Integer, Integer, Integer, Double> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
