/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables;


import gov.epa.bencloud.server.database.jooq.grids.Grids;
import gov.epa.bencloud.server.database.jooq.grids.Indexes;
import gov.epa.bencloud.server.database.jooq.grids.Keys;
import gov.epa.bencloud.server.database.jooq.grids.tables.records.UsCensusTracts_2020Record;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsCensusTracts_2020 extends TableImpl<UsCensusTracts_2020Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>grids.us_census_tracts_2020</code>
     */
    public static final UsCensusTracts_2020 US_CENSUS_TRACTS_2020 = new UsCensusTracts_2020();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsCensusTracts_2020Record> getRecordType() {
        return UsCensusTracts_2020Record.class;
    }

    /**
     * The column <code>grids.us_census_tracts_2020.gid</code>.
     */
    public final TableField<UsCensusTracts_2020Record, Integer> GID = createField(DSL.name("gid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>grids.us_census_tracts_2020.row</code>.
     */
    public final TableField<UsCensusTracts_2020Record, BigDecimal> ROW = createField(DSL.name("row"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_census_tracts_2020.col</code>.
     */
    public final TableField<UsCensusTracts_2020Record, BigDecimal> COL = createField(DSL.name("col"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_census_tracts_2020.area_km</code>.
     */
    public final TableField<UsCensusTracts_2020Record, BigDecimal> AREA_KM = createField(DSL.name("area_km"), SQLDataType.NUMERIC, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public final TableField<UsCensusTracts_2020Record, Object> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "");

    private UsCensusTracts_2020(Name alias, Table<UsCensusTracts_2020Record> aliased) {
        this(alias, aliased, null);
    }

    private UsCensusTracts_2020(Name alias, Table<UsCensusTracts_2020Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>grids.us_census_tracts_2020</code> table
     * reference
     */
    public UsCensusTracts_2020(String alias) {
        this(DSL.name(alias), US_CENSUS_TRACTS_2020);
    }

    /**
     * Create an aliased <code>grids.us_census_tracts_2020</code> table
     * reference
     */
    public UsCensusTracts_2020(Name alias) {
        this(alias, US_CENSUS_TRACTS_2020);
    }

    /**
     * Create a <code>grids.us_census_tracts_2020</code> table reference
     */
    public UsCensusTracts_2020() {
        this(DSL.name("us_census_tracts_2020"), null);
    }

    public <O extends Record> UsCensusTracts_2020(Table<O> child, ForeignKey<O, UsCensusTracts_2020Record> key) {
        super(child, key, US_CENSUS_TRACTS_2020);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Grids.GRIDS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.US_CENSUS_TRACTS_2020_GEOM_IDX);
    }

    @Override
    public Identity<UsCensusTracts_2020Record, Integer> getIdentity() {
        return (Identity<UsCensusTracts_2020Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsCensusTracts_2020Record> getPrimaryKey() {
        return Keys.US_CENSUS_TRACTS_2020_PKEY;
    }

    @Override
    public UsCensusTracts_2020 as(String alias) {
        return new UsCensusTracts_2020(DSL.name(alias), this);
    }

    @Override
    public UsCensusTracts_2020 as(Name alias) {
        return new UsCensusTracts_2020(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCensusTracts_2020 rename(String name) {
        return new UsCensusTracts_2020(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCensusTracts_2020 rename(Name name) {
        return new UsCensusTracts_2020(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, BigDecimal, BigDecimal, BigDecimal, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
