/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables;


import gov.epa.bencloud.server.database.jooq.grids.Grids;
import gov.epa.bencloud.server.database.jooq.grids.Indexes;
import gov.epa.bencloud.server.database.jooq.grids.Keys;
import gov.epa.bencloud.server.database.jooq.grids.tables.records.UsCmaq_12kmNationStraightclipRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsCmaq_12kmNationStraightclip extends TableImpl<UsCmaq_12kmNationStraightclipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>grids.us_cmaq_12km_nation_straightclip</code>
     */
    public static final UsCmaq_12kmNationStraightclip US_CMAQ_12KM_NATION_STRAIGHTCLIP = new UsCmaq_12kmNationStraightclip();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsCmaq_12kmNationStraightclipRecord> getRecordType() {
        return UsCmaq_12kmNationStraightclipRecord.class;
    }

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.gid</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, Integer> GID = createField(DSL.name("gid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.area</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> AREA = createField(DSL.name("area"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.perimeter</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> PERIMETER = createField(DSL.name("perimeter"), SQLDataType.NUMERIC, this, "");

    /**
     * The column
     * <code>grids.us_cmaq_12km_nation_straightclip.combo12km_</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> COMBO12KM_ = createField(DSL.name("combo12km_"), SQLDataType.NUMERIC, this, "");

    /**
     * The column
     * <code>grids.us_cmaq_12km_nation_straightclip.combo12km1</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> COMBO12KM1 = createField(DSL.name("combo12km1"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.col</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> COL = createField(DSL.name("col"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.row</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> ROW = createField(DSL.name("row"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.newcr</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> NEWCR = createField(DSL.name("newcr"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.euscol</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> EUSCOL = createField(DSL.name("euscol"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.eusrow</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> EUSROW = createField(DSL.name("eusrow"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.euscr</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> EUSCR = createField(DSL.name("euscr"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.wuscol</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> WUSCOL = createField(DSL.name("wuscol"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.wusrow</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> WUSROW = createField(DSL.name("wusrow"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>grids.us_cmaq_12km_nation_straightclip.wuscr</code>.
     */
    public final TableField<UsCmaq_12kmNationStraightclipRecord, BigDecimal> WUSCR = createField(DSL.name("wuscr"), SQLDataType.NUMERIC, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public final TableField<UsCmaq_12kmNationStraightclipRecord, Object> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "");

    private UsCmaq_12kmNationStraightclip(Name alias, Table<UsCmaq_12kmNationStraightclipRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsCmaq_12kmNationStraightclip(Name alias, Table<UsCmaq_12kmNationStraightclipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>grids.us_cmaq_12km_nation_straightclip</code>
     * table reference
     */
    public UsCmaq_12kmNationStraightclip(String alias) {
        this(DSL.name(alias), US_CMAQ_12KM_NATION_STRAIGHTCLIP);
    }

    /**
     * Create an aliased <code>grids.us_cmaq_12km_nation_straightclip</code>
     * table reference
     */
    public UsCmaq_12kmNationStraightclip(Name alias) {
        this(alias, US_CMAQ_12KM_NATION_STRAIGHTCLIP);
    }

    /**
     * Create a <code>grids.us_cmaq_12km_nation_straightclip</code> table
     * reference
     */
    public UsCmaq_12kmNationStraightclip() {
        this(DSL.name("us_cmaq_12km_nation_straightclip"), null);
    }

    public <O extends Record> UsCmaq_12kmNationStraightclip(Table<O> child, ForeignKey<O, UsCmaq_12kmNationStraightclipRecord> key) {
        super(child, key, US_CMAQ_12KM_NATION_STRAIGHTCLIP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Grids.GRIDS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.US_CMAQ_12KM_NATION_STRAIGHTCLIP_GEOM_IDX);
    }

    @Override
    public Identity<UsCmaq_12kmNationStraightclipRecord, Integer> getIdentity() {
        return (Identity<UsCmaq_12kmNationStraightclipRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsCmaq_12kmNationStraightclipRecord> getPrimaryKey() {
        return Keys.US_CMAQ_12KM_NATION_STRAIGHTCLIP_PKEY;
    }

    @Override
    public UsCmaq_12kmNationStraightclip as(String alias) {
        return new UsCmaq_12kmNationStraightclip(DSL.name(alias), this);
    }

    @Override
    public UsCmaq_12kmNationStraightclip as(Name alias) {
        return new UsCmaq_12kmNationStraightclip(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCmaq_12kmNationStraightclip rename(String name) {
        return new UsCmaq_12kmNationStraightclip(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCmaq_12kmNationStraightclip rename(Name name) {
        return new UsCmaq_12kmNationStraightclip(name, null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Object> fieldsRow() {
        return (Row15) super.fieldsRow();
    }
}
