/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables;


import gov.epa.bencloud.server.database.jooq.grids.Grids;
import gov.epa.bencloud.server.database.jooq.grids.Indexes;
import gov.epa.bencloud.server.database.jooq.grids.Keys;
import gov.epa.bencloud.server.database.jooq.grids.tables.records.UsCounty_2020Record;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row21;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsCounty_2020 extends TableImpl<UsCounty_2020Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>grids.us_county_2020</code>
     */
    public static final UsCounty_2020 US_COUNTY_2020 = new UsCounty_2020();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsCounty_2020Record> getRecordType() {
        return UsCounty_2020Record.class;
    }

    /**
     * The column <code>grids.us_county_2020.gid</code>.
     */
    public final TableField<UsCounty_2020Record, Integer> GID = createField(DSL.name("gid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>grids.us_county_2020.statefp</code>.
     */
    public final TableField<UsCounty_2020Record, String> STATEFP = createField(DSL.name("statefp"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>grids.us_county_2020.countyfp</code>.
     */
    public final TableField<UsCounty_2020Record, String> COUNTYFP = createField(DSL.name("countyfp"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>grids.us_county_2020.countyns</code>.
     */
    public final TableField<UsCounty_2020Record, String> COUNTYNS = createField(DSL.name("countyns"), SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>grids.us_county_2020.geoid</code>.
     */
    public final TableField<UsCounty_2020Record, String> GEOID = createField(DSL.name("geoid"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>grids.us_county_2020.name</code>.
     */
    public final TableField<UsCounty_2020Record, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>grids.us_county_2020.namelsad</code>.
     */
    public final TableField<UsCounty_2020Record, String> NAMELSAD = createField(DSL.name("namelsad"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>grids.us_county_2020.lsad</code>.
     */
    public final TableField<UsCounty_2020Record, String> LSAD = createField(DSL.name("lsad"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>grids.us_county_2020.classfp</code>.
     */
    public final TableField<UsCounty_2020Record, String> CLASSFP = createField(DSL.name("classfp"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>grids.us_county_2020.mtfcc</code>.
     */
    public final TableField<UsCounty_2020Record, String> MTFCC = createField(DSL.name("mtfcc"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>grids.us_county_2020.csafp</code>.
     */
    public final TableField<UsCounty_2020Record, String> CSAFP = createField(DSL.name("csafp"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>grids.us_county_2020.cbsafp</code>.
     */
    public final TableField<UsCounty_2020Record, String> CBSAFP = createField(DSL.name("cbsafp"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>grids.us_county_2020.metdivfp</code>.
     */
    public final TableField<UsCounty_2020Record, String> METDIVFP = createField(DSL.name("metdivfp"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>grids.us_county_2020.funcstat</code>.
     */
    public final TableField<UsCounty_2020Record, String> FUNCSTAT = createField(DSL.name("funcstat"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>grids.us_county_2020.aland</code>.
     */
    public final TableField<UsCounty_2020Record, Double> ALAND = createField(DSL.name("aland"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>grids.us_county_2020.awater</code>.
     */
    public final TableField<UsCounty_2020Record, Double> AWATER = createField(DSL.name("awater"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>grids.us_county_2020.intptlat</code>.
     */
    public final TableField<UsCounty_2020Record, String> INTPTLAT = createField(DSL.name("intptlat"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>grids.us_county_2020.intptlon</code>.
     */
    public final TableField<UsCounty_2020Record, String> INTPTLON = createField(DSL.name("intptlon"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>grids.us_county_2020.col</code>.
     */
    public final TableField<UsCounty_2020Record, Integer> COL = createField(DSL.name("col"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>grids.us_county_2020.row</code>.
     */
    public final TableField<UsCounty_2020Record, Integer> ROW = createField(DSL.name("row"), SQLDataType.INTEGER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public final TableField<UsCounty_2020Record, Object> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "");

    private UsCounty_2020(Name alias, Table<UsCounty_2020Record> aliased) {
        this(alias, aliased, null);
    }

    private UsCounty_2020(Name alias, Table<UsCounty_2020Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>grids.us_county_2020</code> table reference
     */
    public UsCounty_2020(String alias) {
        this(DSL.name(alias), US_COUNTY_2020);
    }

    /**
     * Create an aliased <code>grids.us_county_2020</code> table reference
     */
    public UsCounty_2020(Name alias) {
        this(alias, US_COUNTY_2020);
    }

    /**
     * Create a <code>grids.us_county_2020</code> table reference
     */
    public UsCounty_2020() {
        this(DSL.name("us_county_2020"), null);
    }

    public <O extends Record> UsCounty_2020(Table<O> child, ForeignKey<O, UsCounty_2020Record> key) {
        super(child, key, US_COUNTY_2020);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Grids.GRIDS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.US_COUNTY_2020_GEOM_IDX);
    }

    @Override
    public Identity<UsCounty_2020Record, Integer> getIdentity() {
        return (Identity<UsCounty_2020Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsCounty_2020Record> getPrimaryKey() {
        return Keys.US_COUNTY_2020_PKEY;
    }

    @Override
    public UsCounty_2020 as(String alias) {
        return new UsCounty_2020(DSL.name(alias), this);
    }

    @Override
    public UsCounty_2020 as(Name alias) {
        return new UsCounty_2020(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCounty_2020 rename(String name) {
        return new UsCounty_2020(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCounty_2020 rename(Name name) {
        return new UsCounty_2020(name, null);
    }

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Double, Double, String, String, Integer, Integer, Object> fieldsRow() {
        return (Row21) super.fieldsRow();
    }
}
